name: Exemplo de Ação GitHub

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Adicionando a opção de execução manual

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Definir variável de ambiente a partir do segredo
        run: |
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar requests
        run: |
          pip install requests  # Instala a biblioteca requests, se necessário

      - name: Executar main.py
        run: |
          python main.py  # Executa o script Python
